#SPRING
spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.150:3306/xn_test
    username: root
    password: xueneng5404
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true