#SPRING
spring:
  output:
    ansi:
      enabled: always
#REDIS
  redis:
    host: localhost
    port: 6379
    database: 1
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 500
      min-idle: 0
    timeout: 0

